#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import copy
import json
import os
import time

JOB_INFOS_CMD_ARM = 'source @SCHEDULER_PROFILE_PATH@;' \
                'timeout 10 bjobs -a -u all -hms -o \"jobid jobindex job_name user source_cluster stat ' \
                'queue from_host submit_time start_time finish_time exec_home output_dir output_file error_file job_priority ' \
                'exec_host job_description exit_code pend_reason run_time cpu_used mem avg_mem max_mem swap cpu_used gpu_num gpu_alloc slots nreq_slot nalloc_slot alloc_slot delimiter=\'^\'\"'

JOB_INFOS_CMD_X86 = 'source @SCHEDULER_PROFILE_PATH@;' \
                'timeout 10 bjobs -a -u all -hms -o \"jobid jobindex job_name user source_cluster stat ' \
                'queue from_host submit_time start_time finish_time exec_home output_dir output_file error_file job_priority ' \
                'exec_host job_description exit_code pend_reason run_time cpu_used mem avg_mem max_mem swap cpu_used slots nalloc_slot alloc_slot delimiter=\'^\'\"'

ARRAY_JOB_INFO_CMD = 'source @SCHEDULER_PROFILE_PATH@; timeout 10 bjobs -A -w '

statMap = {'UNKWN': -1, 'RUN': 4, 'PSUSP': 2, 'USUSP': 2, 'SSUSP': 10, 'PEND': 1, 'DONE': 9, 'EXIT': 5, 'WAIT': 3, 'ZOMBI': -1}

jobFields_arm = ['JOBID', 'JOBINDEX', 'JOB_NAME', 'USER', 'SOURCE_CLUSTER', 'STAT', 'QUEUE', 'FROM_HOST', 'SUBMIT_TIME',
             'START_TIME', 'FINISH_TIME', 'EXEC_HOME', 'OUTPUT_DIR', 'OUTPUT_FILE', 'ERROR_FILE', 'JOB_PRIORITY',
             'EXEC_HOST', 'JOB_DESCRIPTION', 'EXIT_CODE', 'PEND_REASON', 'RUN_TIME', 'CPU_USED', 'MEM', 'AVG_MEM',
             'MAX_MEM', 'SWAP', 'CPU_USED', 'GPU_NUM', 'GPU_ALLOC', 'SLOTS', 'NREQ_SLOT', 'NALLOC_SLOT', 'ALLOC_SLOT']

jobFields_x86 = ['JOBID', 'JOBINDEX', 'JOB_NAME', 'USER', 'SOURCE_CLUSTER', 'STAT', 'QUEUE', 'FROM_HOST', 'SUBMIT_TIME',
             'START_TIME', 'FINISH_TIME', 'EXEC_HOME', 'OUTPUT_DIR', 'OUTPUT_FILE', 'ERROR_FILE', 'JOB_PRIORITY',
             'EXEC_HOST', 'JOB_DESCRIPTION', 'EXIT_CODE', 'PEND_REASON', 'RUN_TIME', 'CPU_USED', 'MEM', 'AVG_MEM',
             'MAX_MEM', 'SWAP', 'CPU_USED', 'SLOTS', 'NALLOC_SLOT', 'ALLOC_SLOT']

def aggJobState(parentJobinfo, arrayJobStatArr):
    if len(arrayJobStatArr) < 7:
        parentJobinfo['stat'] = 'UNKWN'
        return
    runNum = int(arrayJobStatArr[2])
    if runNum > 0:
        parentJobinfo['stat'] = 'RUN'
        return
    usupNum = int(arrayJobStatArr[4])
    if usupNum > 0:
        parentJobinfo['stat'] = 'USUSP'
        return
    ssuspNum = int(arrayJobStatArr[5])
    if ssuspNum > 0:
        parentJobinfo['stat'] = 'SSUSP'
        return
    pendNum = int(arrayJobStatArr[0])
    if pendNum > 0:
        parentJobinfo['stat'] = 'PEND'
        return
    exitNum = int(arrayJobStatArr[3])
    if exitNum > 0:
        parentJobinfo['stat'] = 'EXIT'
        return
    doneNum = int(arrayJobStatArr[1])
    if doneNum > 0:
        parentJobinfo['stat'] = 'DONE'
        return
        doneNum = int(arrayJobStatArr[6])
    if doneNum > 0:
        parentJobinfo['stat'] = 'ZOMBI'
        return
    parentJobinfo['stat'] = 'UNKWN'
    return

def getOrder():
    if(os.popen('uname -a').read().__contains__('x86')):
        return JOB_INFOS_CMD_X86
    return JOB_INFOS_CMD_ARM

def strToJson(jobInfoStr):
    jobInfoArr = jobInfoStr.split("^")
    jobInfo = {}
    if len(jobInfoArr) == len(jobFields_arm):
        for index in range(len(jobFields_arm)):
            field = jobInfoArr[index]
            if field == '-':
                field = ''
            jobInfo[jobFields_arm[index]] = field
        return jobInfo
    if len(jobInfoArr) == len(jobFields_x86):
        for index in range(len(jobFields_x86)):
            field = jobInfoArr[index]
            if field == '-':
                field = ''
            jobInfo[jobFields_x86[index]] = field
        jobInfo['NREQ_SLOT'] = ''
        jobInfo['GPU_NUM'] = ''
        jobInfo['GPU_ALLOC'] = ''
        return jobInfo

jobInfos = os.popen(getOrder()).read()
jobInfosArr = jobInfos.strip().split("\n")

# 构造非数组作业及数组作业子作业信息 及数组作业状态表
outputJobList = []

timeresult = time.localtime(time.time())
timelist = list(timeresult)
timelist[4] = int(timeresult.tm_min/5)*5
timelist[5] = 0
timeresult = tuple(timelist)
result = time.localtime(time.mktime(timeresult))
sampletime = time.strftime('%Y/%m/%d %H:%M:%S',result)

for index in range(len(jobInfosArr)):
    if index == 0:
        continue
    jobInfo = strToJson(jobInfosArr[index])
    jobInfo['OUTPUT_DIR'] = jobInfo['OUTPUT_DIR'].rstrip('/')
    if not statMap.has_key(jobInfo['STAT']):
        statMap[jobInfo['STAT']]=-1
    # 替换key值为期望解析值
    outputJob = {'jobId': jobInfo['JOBID'], 'jobIndex': int(jobInfo['JOBINDEX']), 'jobName': jobInfo['JOB_NAME'],
                 'user': jobInfo['USER'], 'cluster': jobInfo['SOURCE_CLUSTER'],
                 'stat': str(statMap[jobInfo['STAT']]),
                 'queue': jobInfo['QUEUE'], 'fromHost': jobInfo['FROM_HOST'], 'submitTime': jobInfo['SUBMIT_TIME'],
                 'startTime': jobInfo['START_TIME'], 'finishTime': jobInfo['FINISH_TIME'],
                 'execHome': jobInfo['OUTPUT_DIR'], 'outputFile': jobInfo['OUTPUT_FILE'],
                 'errorFile': jobInfo['ERROR_FILE'], 'jobPriority': jobInfo['JOB_PRIORITY'],
                 'execHost': jobInfo['EXEC_HOST'], 'jobDescription': jobInfo['JOB_DESCRIPTION'],
                 'exitCode': jobInfo['EXIT_CODE'], 'pendReason': jobInfo['PEND_REASON'],
                 'jobRunTime': jobInfo['RUN_TIME'], 'originState': jobInfo['STAT'],
                 'resReq': {
                     'cpu': jobInfo['NREQ_SLOT'] if jobInfo['NREQ_SLOT'] != '' else None,
                     'mem': None,
                     'gpu': None
                 },
                 'resAlloc': {
                     'cpu': jobInfo['NALLOC_SLOT'] if jobInfo['NALLOC_SLOT'] != '' else None,
                     'mem': None,
                     'gpu': jobInfo['GPU_ALLOC'] if jobInfo['GPU_ALLOC'] != '' else None
                 },
                 'rusage': {
                     'memAvg': jobInfo['AVG_MEM'] if jobInfo['AVG_MEM'] != '' else None,
                     'memMax': jobInfo['MAX_MEM'] if jobInfo['MAX_MEM'] != '' else None,
                     'memReal': jobInfo['MEM'] if jobInfo['MEM'] != '' else None,
                     'swap': jobInfo['SWAP'],
                     'swapMax': None,
                     'rss': None,
                     'cache': None
                 },
                 'timeStampL': sampletime}

    if outputJob['execHome'] == '':
        outputJob['execHome'] = jobInfo['EXEC_HOME']
    jobId = outputJob['jobId']
    arrayJobInfo = os.popen(ARRAY_JOB_INFO_CMD + jobId).read().splitlines()
    # 判断是否为数组作业
    if len(arrayJobInfo) == 2:
        arrayJobInfoValue = arrayJobInfo[1].split()
        if len(arrayJobInfoValue) > 2:
            outputJob['jobId'] = "{}.{}".format(jobId, outputJob['jobIndex'])
            outputJob['jobIndex'] = 0
    outputJobList.append(outputJob)

outputStr = json.dumps(outputJobList)
print(outputStr)
