#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os

USERS_CMD = 'source @SCHEDULER_PROFILE_PATH@; timeout 10 busers all' 

arrayUsersInfo = os.popen(USERS_CMD).read().splitlines()

print(len(arrayUsersInfo) - 1)